[workspace]
resolver = "2"
default-members = ["crates/rune"]
members = [
    "crates/diagnostics",
    "crates/sindr",
    "crates/spire",
    "crates/sigil",
    "crates/scar",
    "crates/forge",
    "crates/eldr",
    "crates/xldr",
    "crates/rune",
]

[workspace.dependencies]
num-bigint = { version = "0.4", features = ["serde"] }
num-traits = "0.2"
