created: 2026-04-09T14:03:39.272Z
updated: 2026-04-09T14:03:39.278Z
update_count: 1
last_field: description
kind: nested-class
title: run-command
children: []
parentPath:
  - rune-cli
  - command-implementations
